`ifndef BP_COMMON_AVIARY_CUSTOM_DEFINES_SVH
`define BP_COMMON_AVIARY_CUSTOM_DEFINES_SVH


`define BP_PREFETCH_STREAMS 2
`define BP_PREFETCH_TRAIN_CNT 3
`define BP_PREFETCH_LOOKAHEAD_DEPTH 2
`define BP_PREFETCH_IDLE_THRESHOLD 3
`define BP_PREFETCH_EN 1

`endif
